In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
print(a)
print(a.shape)

[1 2 3 4]
(4,)


# Using reshape() method

In [3]:
# Using reshape method
b = a.reshape(-1,1)
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]]
(4, 1)


In [4]:
c = a.reshape(1,-1)
print(c)
print(c.shape)

[[1 2 3 4]]
(1, 4)


# Using expand_dims() function

In [5]:
d = np.expand_dims(a, axis=1)
print(d)
print(d.shape)

[[1]
 [2]
 [3]
 [4]]
(4, 1)


In [6]:
e = np.expand_dims(a, axis=0)
print(e)
print(e.shape)

[[1 2 3 4]]
(1, 4)


# Using np.newaxis Argument

In [7]:
f = a[np.newaxis, ...]
print(f)
print(f.shape)

[[1 2 3 4]]
(1, 4)
