In [1]:
import numpy as np

In [2]:
revenue = np.array([[180,200,220],[24,36,40],[12,18,20]])
expenses = np.array([[80,90,100],[10,16,20],[8,10,10]])

In [3]:
revenue

array([[180, 200, 220],
       [ 24,  36,  40],
       [ 12,  18,  20]])

In [4]:
expenses

array([[ 80,  90, 100],
       [ 10,  16,  20],
       [  8,  10,  10]])

# Matrix subtraction

In [5]:
profits = revenue - expenses
profits

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [6]:
price_per_unit = np.array([1000,400,1200])
sold_units = np.array([[30,40,50],[5,10,15],[2,5,7]])

In [7]:
price_per_unit

array([1000,  400, 1200])

In [8]:
sold_units

array([[30, 40, 50],
       [ 5, 10, 15],
       [ 2,  5,  7]])

# Numpy Broad-Casting

In [9]:
total_sales = price_per_unit  * sold_units
total_sales

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

# Matrix Multiplication

In [10]:
total_sales = np.dot(price_per_unit,sold_units)
total_sales

array([34400, 50000, 64400])

# Converting Dollar to Rupee

In [11]:
revenue_dollar = np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])
revenue_dollar

array([[200, 220, 250],
       [ 68,  79, 105],
       [110, 140, 180],
       [ 80,  85,  90]])

In [12]:
revenue_rupee = revenue_dollar * 75
revenue_rupee

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

# Getting sales of each month

In [13]:
units_sold = np.array([[50,60,25],[10,13,5],[40,70,52]])
price_per_unit = np.array([20,30,15])

In [14]:
total_sales = np.dot(units_sold,price_per_unit)

In [15]:
total_sales

array([3175,  665, 3680])