In [28]:
!pip install tensorflow

In [29]:
# importing librraies
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [30]:
# load the dataset
df = pd.read_excel("/content/simple_insurance.xlsx")
df

age  affordability  insurance
0    22              1          0
1    25              0          0
2    47              1          1
3    52              0          0
4    46              1          1
5    56              1          1
6    55              0          0
7    60              0          1
8    62              1          1
9    61              1          1
10   18              1          0
11   28              1          0
12   27              0          1
13   34              1          0
14   70              0          1
15   46              1          1
16   22              0          0
17   28              1          1
18   35              1          0
19   66              0          1
20   29              1          1
21   17              0          0
22   32              0          0
23   49              0          1
24   35              1          1
25   55              1          0

In [31]:
# Extracting Dependent and Independent variable
x = df.drop(["insurance"], axis=1)
y = df["insurance"]

In [32]:
x

age  affordability
0    22              1
1    25              0
2    47              1
3    52              0
4    46              1
5    56              1
6    55              0
7    60              0
8    62              1
9    61              1
10   18              1
11   28              1
12   27              0
13   34              1
14   70              0
15   46              1
16   22              0
17   28              1
18   35              1
19   66              0
20   29              1
21   17              0
22   32              0
23   49              0
24   35              1
25   55              1

In [33]:
# Scaling age column value from 0 to 1
x["age"] = x["age"]/100
x

age  affordability
0   0.22              1
1   0.25              0
2   0.47              1
3   0.52              0
4   0.46              1
5   0.56              1
6   0.55              0
7   0.60              0
8   0.62              1
9   0.61              1
10  0.18              1
11  0.28              1
12  0.27              0
13  0.34              1
14  0.70              0
15  0.46              1
16  0.22              0
17  0.28              1
18  0.35              1
19  0.66              0
20  0.29              1
21  0.17              0
22  0.32              0
23  0.49              0
24  0.35              1
25  0.55              1

In [34]:
y

0     0
1     0
2     1
3     0
4     1
5     1
6     0
7     1
8     1
9     1
10    0
11    0
12    1
13    0
14    1
15    1
16    0
17    1
18    0
19    1
20    1
21    0
22    0
23    1
24    1
25    0
Name: insurance, dtype: int64

In [35]:
# Splitting the dataset into train and test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=2023)

In [36]:
print(x.shape, x_train.shape, x_test.shape)

(26, 2) (20, 2) (6, 2)


In [37]:
x_train

age  affordability
18  0.35              1
24  0.35              1
22  0.32              0
21  0.17              0
2   0.47              1
8   0.62              1
16  0.22              0
7   0.60              0
13  0.34              1
19  0.66              0
15  0.46              1
17  0.28              1
0   0.22              1
5   0.56              1
20  0.29              1
3   0.52              0
1   0.25              0
25  0.55              1
6   0.55              0
23  0.49              0

In [38]:
x_test

age  affordability
9   0.61              1
12  0.27              0
4   0.46              1
10  0.18              1
14  0.70              0
11  0.28              1

In [39]:
# Training the model on tensorflow
# Initializing co-efficient(w1,w2) as 1 and intercept as 0
model = keras.Sequential([
    keras.layers.Dense(1, input_shape=(2,), activation="sigmoid", kernel_initializer="ones", bias_initializer="zeros")
])

# Compile the model
model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

# Fitting the model
model.fit(x_train, y_train, epochs=5000)

Streaming output truncated to the last 5000 lines.
1/1 [==============================] - 0s 9ms/step - loss: 0.6080 - accuracy: 0.6500
Epoch 1820/5000
1/1 [==============================] - 0s 9ms/step - loss: 0.6079 - accuracy: 0.6500
Epoch 1821/5000
1/1 [==============================] - 0s 15ms/step - loss: 0.6079 - accuracy: 0.6500
Epoch 1822/5000
1/1 [==============================] - 0s 9ms/step - loss: 0.6079 - accuracy: 0.6500
Epoch 1823/5000
1/1 [==============================] - 0s 9ms/step - loss: 0.6079 - accuracy: 0.6500
Epoch 1824/5000
1/1 [==============================] - 0s 9ms/step - loss: 0.6078 - accuracy: 0.6500
Epoch 1825/5000
1/1 [==============================] - 0s 9ms/step - loss: 0.6078 - accuracy: 0.6500
Epoch 1826/5000
1/1 [==============================] - 0s 9ms/step - loss: 0.6078 - accuracy: 0.6500
Epoch 1827/5000
1/1 [==============================] - 0s 9ms/step - loss: 0.6077 - accuracy: 0.6500
Epoch 1828/5000
1/1 [==============================] - 

In [40]:
# Evaluate the model
model.evaluate(x_test, y_test)

1/1 [==============================] - 0s 200ms/step - loss: 0.6411 - accuracy: 0.6667


[0.6410511136054993, 0.6666666865348816]

In [41]:
# Prediction of test dataset
y_predicted = model.predict(x_test)
y_predicted


1/1 [==============================] - 0s 65ms/step


array([[0.8159968 ],
       [0.2029038 ],
       [0.6960067 ],
       [0.39994213],
       [0.62876445],
       [0.5087564 ]], dtype=float32)

Value grater than 0.50 is 1 and less than 0.5 is 0

In [42]:
# Actual Value
y_test

9     1
12    1
4     1
10    0
14    1
11    0
Name: insurance, dtype: int64

# Creating Custom Prediction Function

In [43]:
# Co-efficient and intercepets of tf model
co_ef, intercept = model.get_weights()
co_ef, intercept

(array([[4.4073567],
        [1.3591992]], dtype=float32),
 array([-2.5582297], dtype=float32))

In [44]:

# Creating sigmoid function
def sigmoid(x):
  import math
  return 1 / (1 + math.exp(-x))

sigmoid(40)

1.0

In [45]:
# custom prediction function
def custom_prediction(age, affordability):
  weighted_sum = co_ef[0]*age + co_ef[1]*affordability + intercept
  return sigmoid(weighted_sum)

In [46]:
# prediction for 0.47 age and 1 affordability
custom_prediction(0.47, 1)

0.7052505019385769

In [47]:
# prediction for 0.22 age and 1 affordability
custom_prediction(0.22, 1)

0.44289720376130176

Gradient Descent from Scratch

In [48]:
# creating Log Loss function
def log_loss(y_true, y_predicted):
  epsilon = 1e-15
  y_predicted_new = [max(x, epsilon) for x in y_predicted]
  y_predicted_new = [min(x, 1 - epsilon) for x in y_predicted_new]
  y_predicted_new = np.array(y_predicted_new)
  # y_predicted_new = np.clip(y_predicted, epsilon, 1 - epsilon)
  # epsilon = 1e-15 = 0.000000000000001 <==> 1-epsilon = 0.999999999999999
  return -np.mean(y_true * np.log(y_predicted_new) + (1 - y_true) * np.log(1 - y_predicted_new))


In [49]:
# Creating sigmoid function
def sigmoid_numpy(X):
  import numpy
  return 1/(1+np.exp(-X))

sigmoid_numpy(np.array([40,20,0,-43]))

array([1.00000000e+00, 9.99999998e-01, 5.00000000e-01, 2.11513104e-19])

In [50]:
# gradient descent
def gradient_descent(age, affordability , y_true, epochs, loss_threshold):

  # initializing w1, w2, bias
  w1 = w2 = 1
  bias = 0
  n = len(age)
  rate = 0.5

  for i in range(epochs):
    weighted_sum = w1*age + w2*affordability + bias
    y_predicted = sigmoid_numpy(weighted_sum)

    # defining loss
    loss = log_loss(y_true, y_predicted)

    # Updating w1, w2, bias based on d(deriavative)
    w1_d = (1/n)*np.dot(np.transpose(age), (y_predicted - y_true))
    w2_d = (1/n)*np.dot(np.transpose(affordability), (y_predicted - y_true))
    bias_d = np.mean(y_predicted - y_true)

    w1 = w1 - rate * w1_d
    w2 = w2 - rate * w2_d
    bias = bias - rate * bias_d

    print(f"Epoch:{i} w1:{w1} w2:{w2}, bias:{bias} loss:{loss}")

    if loss<=loss_threshold:
      break

  return w1, w2, bias

In [51]:
gradient_descent(x_train["age"], x_train["affordability"], y_train, 1000, 0.5469)

Epoch:0 w1:0.9701852122868726 w2:0.9542484502922418, bias:-0.10637616003926767 loss:0.7243577306973332
Epoch:1 w1:0.9460912374553797 w2:0.9159762381726181, bias:-0.19884889044724302 loss:0.6977312147860237
Epoch:2 w1:0.927190926264331 w2:0.8846649069755276, bias:-0.27872085527073176 loss:0.6780816624443672
Epoch:3 w1:0.9128958340206997 w2:0.8596367811144824, bias:-0.3474333118619664 loss:0.6638148680113853
Epoch:4 w1:0.9026072868519166 w2:0.8401398233370245, bias:-0.4064443332190021 loss:0.6535687276233676
Epoch:5 w1:0.8957529134576502 w2:0.8254149007355421, bias:-0.45714247767666305 loss:0.6462488990716068
Epoch:6 w1:0.8918087503764283 w2:0.8147413973891615, bias:-0.5007952031190153 loss:0.6410163626585625
Epoch:7 w1:0.8903097487723142 w2:0.8074634244341807, bias:-0.5385249767857911 loss:0.6372501646722096
Epoch:8 w1:0.8908522090698373 w2:0.8030014104459466, bias:-0.5713045092370718 loss:0.6345027169744901
Epoch:9 w1:0.8930912531335223 w2:0.8008539668151811, bias:-0.5999636370618924 l

(4.406416040083875, 1.3693692942963225, -2.573361280320135)

Using Plain Python

*   w1 = 4.406
*   w2 = 1.369
*   bias = -2.573



In [52]:
# from tensorflow, we got
w1 = co_ef[0]
w2 = co_ef[1]
bias = intercept
print(w1, w2, bias)

[4.4073567] [1.3591992] [-2.5582297]


Using ChatGPT

In [54]:
import numpy as np

# Log Loss Function
def log_loss(y_true, y_predicted):
    epsilon = 1e-15
    y_predicted_new = np.clip(y_predicted, epsilon, 1 - epsilon)
    return -np.mean(y_true * np.log(y_predicted_new) + (1 - y_true) * np.log(1 - y_predicted_new))

# Sigmoid Function
def sigmoid_numpy(X):
    return 1 / (1 + np.exp(-X))

# Gradient Descent Function
def gradient_descent(X, y_true, epochs, loss_threshold):
    n_samples, n_features = X.shape
    rate = 0.5

    # Initializing weights and bias
    w = np.ones(n_features)
    bias = 0

    for epoch in range(epochs):
        weighted_sum = np.dot(X, w) + bias
        y_predicted = sigmoid_numpy(weighted_sum)

        # Calculating loss
        loss = log_loss(y_true, y_predicted)

        # Calculating gradients
        w_gradients = (1/n_samples) * np.dot(X.T, (y_predicted - y_true))
        bias_gradient = np.mean(y_predicted - y_true)

        # Updating weights and bias
        w -= rate * w_gradients
        bias -= rate * bias_gradient

        print(f"Epoch:{epoch} Loss:{loss}")

        if loss <= loss_threshold:
            break

    return w, bias

# Assuming you have x_train and y_train as input data
# Assuming x_train has shape (n_samples, n_features)
x_train = np.array(x_train)  # Your training data
y_train = np.array(y_train)  # Your binary labels

# Performing gradient descent
optimal_w, optimal_bias = gradient_descent(x_train, y_train, epochs=1000, loss_threshold=0.5469)
print(f"w1:{optimal_w[0]}, w2:{optimal_w[1]}, bias:{optimal_bias}")

Epoch:0 Loss:0.7243577306973332
Epoch:1 Loss:0.6977312147860237
Epoch:2 Loss:0.6780816624443672
Epoch:3 Loss:0.6638148680113853
Epoch:4 Loss:0.6535687276233676
Epoch:5 Loss:0.6462488990716068
Epoch:6 Loss:0.6410163626585625
Epoch:7 Loss:0.6372501646722096
Epoch:8 Loss:0.6345027169744901
Epoch:9 Loss:0.6324576586341449
Epoch:10 Loss:0.6308945934013371
Epoch:11 Loss:0.629661598840169
Epoch:12 Loss:0.628654753827258
Epoch:13 Loss:0.6278033579866491
Epoch:14 Loss:0.627059488317857
Epoch:15 Loss:0.6263907324388138
Epoch:16 Loss:0.6257751876301021
Epoch:17 Loss:0.6251980467018029
Epoch:18 Loss:0.6246492808624857
Epoch:19 Loss:0.624122073923286
Epoch:20 Loss:0.6236117675975301
Epoch:21 Loss:0.6231151527322388
Epoch:22 Loss:0.6226299938111343
Epoch:23 Loss:0.6221547103237699
Epoch:24 Loss:0.6216881634040917
Epoch:25 Loss:0.6212295130058886
Epoch:26 Loss:0.6207781222903694
Epoch:27 Loss:0.620333493589897
Epoch:28 Loss:0.6198952254799883
Epoch:29 Loss:0.619462983958374
Epoch:30 Loss:0.6190364830