In [1]:
!pip install tensorflow

In [2]:
# importing librraies
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# load the dataset
df = pd.read_excel("/content/simple_insurance.xlsx")
df

age  affordability  insurance
0    22              1          0
1    25              0          0
2    47              1          1
3    52              0          0
4    46              1          1
5    56              1          1
6    55              0          0
7    60              0          1
8    62              1          1
9    61              1          1
10   18              1          0
11   28              1          0
12   27              0          1
13   34              1          0
14   70              0          1
15   46              1          1
16   22              0          0
17   28              1          1
18   35              1          0
19   66              0          1
20   29              1          1
21   17              0          0
22   32              0          0
23   49              0          1
24   35              1          1
25   55              1          0

In [4]:
# Extracting Dependent and Independent variable
x = df.drop(["insurance"], axis=1)
y = df["insurance"]

In [5]:
x

age  affordability
0    22              1
1    25              0
2    47              1
3    52              0
4    46              1
5    56              1
6    55              0
7    60              0
8    62              1
9    61              1
10   18              1
11   28              1
12   27              0
13   34              1
14   70              0
15   46              1
16   22              0
17   28              1
18   35              1
19   66              0
20   29              1
21   17              0
22   32              0
23   49              0
24   35              1
25   55              1

In [6]:
# Scaling age column value from 0 to 1
x["age"] = x["age"]/100
x

age  affordability
0   0.22              1
1   0.25              0
2   0.47              1
3   0.52              0
4   0.46              1
5   0.56              1
6   0.55              0
7   0.60              0
8   0.62              1
9   0.61              1
10  0.18              1
11  0.28              1
12  0.27              0
13  0.34              1
14  0.70              0
15  0.46              1
16  0.22              0
17  0.28              1
18  0.35              1
19  0.66              0
20  0.29              1
21  0.17              0
22  0.32              0
23  0.49              0
24  0.35              1
25  0.55              1

In [7]:
y

0     0
1     0
2     1
3     0
4     1
5     1
6     0
7     1
8     1
9     1
10    0
11    0
12    1
13    0
14    1
15    1
16    0
17    1
18    0
19    1
20    1
21    0
22    0
23    1
24    1
25    0
Name: insurance, dtype: int64

In [9]:
# Splitting the dataset into train and test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=2023)

In [10]:
print(x.shape, x_train.shape, x_test.shape)

(26, 2) (20, 2) (6, 2)


In [11]:
x_train

age  affordability
18  0.35              1
24  0.35              1
22  0.32              0
21  0.17              0
2   0.47              1
8   0.62              1
16  0.22              0
7   0.60              0
13  0.34              1
19  0.66              0
15  0.46              1
17  0.28              1
0   0.22              1
5   0.56              1
20  0.29              1
3   0.52              0
1   0.25              0
25  0.55              1
6   0.55              0
23  0.49              0

In [12]:
x_test

age  affordability
9   0.61              1
12  0.27              0
4   0.46              1
10  0.18              1
14  0.70              0
11  0.28              1

In [13]:
# Training the model on tensorflow
# Initializing co-efficient(w1,w2) as 1 and intercept as 0
model = keras.Sequential([
    keras.layers.Dense(1, input_shape=(2,), activation="sigmoid", kernel_initializer="ones", bias_initializer="zeros")
])

# Compile the model
model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

# Fitting the model
model.fit(x_train, y_train, epochs=5000)

Epoch 1/5000
1/1 [==============================] - 1s 1s/step - loss: 0.7244 - accuracy: 0.5000
Epoch 2/5000
1/1 [==============================] - 0s 18ms/step - loss: 0.7240 - accuracy: 0.5000
Epoch 3/5000
1/1 [==============================] - 0s 19ms/step - loss: 0.7236 - accuracy: 0.5000
Epoch 4/5000
1/1 [==============================] - 0s 16ms/step - loss: 0.7233 - accuracy: 0.5000
Epoch 5/5000
1/1 [==============================] - 0s 13ms/step - loss: 0.7229 - accuracy: 0.5000
Epoch 6/5000
1/1 [==============================] - 0s 13ms/step - loss: 0.7225 - accuracy: 0.5000
Epoch 7/5000
1/1 [==============================] - 0s 10ms/step - loss: 0.7222 - accuracy: 0.5000
Epoch 8/5000
1/1 [==============================] - 0s 12ms/step - loss: 0.7218 - accuracy: 0.5000
Epoch 9/5000
1/1 [==============================] - 0s 12ms/step - loss: 0.7215 - accuracy: 0.5000
Epoch 10/5000
1/1 [==============================] - 0s 16ms/step - loss: 0.7211 - accuracy: 0.5000
Epoch 11/50

In [14]:
# Evaluate the model
model.evaluate(x_test, y_test)

1/1 [==============================] - 0s 191ms/step - loss: 0.6411 - accuracy: 0.6667


[0.6410511136054993, 0.6666666865348816]

In [15]:
# Prediction of test dataset
y_predicted = model.predict(x_test)
y_predicted[:5]

1/1 [==============================] - 0s 82ms/step


array([[0.8159968 ],
       [0.20290382],
       [0.6960067 ],
       [0.39994213],
       [0.6287645 ]], dtype=float32)

Value Grater than 0.5 is 1 and Less than 0.5 is 0

In [16]:
# Actual Value
y_test[:5]

9     1
12    1
4     1
10    0
14    1
Name: insurance, dtype: int64

In [17]:
# Co-efficient and intercepets of tf model
co_ef, intercept = model.get_weights()
co_ef, intercept

(array([[4.407357],
        [1.359199]], dtype=float32),
 array([-2.5582297], dtype=float32))

Neural Network using Python

In [18]:
# creating Log Loss function
def log_loss(y_true, y_predicted):
  epsilon = 1e-15
  y_predicted_new = [max(x, epsilon) for x in y_predicted]
  y_predicted_new = [min(x, 1 - epsilon) for x in y_predicted_new]
  y_predicted_new = np.array(y_predicted_new)
  # y_predicted_new = np.clip(y_predicted, epsilon, 1 - epsilon)
  # epsilon = 1e-15 = 0.000000000000001 <==> 1-epsilon = 0.999999999999999
  return -np.mean(y_true * np.log(y_predicted_new) + (1 - y_true) * np.log(1 - y_predicted_new))

In [19]:
# Creating sigmoid function
def sigmoid_numpy(X):
  import numpy
  return 1/(1+np.exp(-X))

sigmoid_numpy(np.array([40,20,0,-43]))

array([1.00000000e+00, 9.99999998e-01, 5.00000000e-01, 2.11513104e-19])

In [22]:
# custom Neural Network class
class myNN:
  # getting input parameters
  def __init__(self):
    self.w1 = 1
    self.w2 = 1
    self.bias = 0

  # custom function for fitting the model
  def fit(self, X, y, epochs, loss_threshold):
    self.w1, self.w2, self.bias = self.gradient_descent(X['age'], X["affordability"], y, epochs, loss_threshold)

  # custom function for predictiction
  def predict(self, x_test):
    weighted_sum = self.w1 * x_test['age'] + self.w2 * x_test["affordability"] + self.bias
    return sigmoid_numpy(weighted_sum)

  # gradient descent function
  def gradient_descent(self, age, affordability , y_true, epochs, loss_threshold):

    # initializing w1, w2, bias
    w1 = w2 = 1
    bias = 0
    n = len(age)
    rate = 0.5

    for epoch in range(epochs):
      weighted_sum = w1*age + w2*affordability + bias
      y_predicted = sigmoid_numpy(weighted_sum)

      # defining loss
      loss = log_loss(y_true, y_predicted)

      # Updating w1, w2, bias based on d(deriavative)
      w1_d = (1/n)*np.dot(np.transpose(age), (y_predicted - y_true))
      w2_d = (1/n)*np.dot(np.transpose(affordability), (y_predicted - y_true))
      bias_d = np.mean(y_predicted - y_true)

      w1 = w1 - rate * w1_d
      w2 = w2 - rate * w2_d
      bias = bias - rate * bias_d

      if epoch % 50 == 0:
        print(f"Epoch:{epoch} w1:{w1} w2:{w2}, bias:{bias} loss:{loss}")

      if loss<=loss_threshold:
        print(f"Epoch:{epoch} w1:{w1} w2:{w2}, bias:{bias} loss:{loss}")
        break

    return w1, w2, bias

In [23]:
# Calling the class
customModel = myNN()
customModel.fit(x_train, y_train, 500, 0.5509)

Epoch:0 w1:0.9701852122868726 w2:0.9542484502922418, bias:-0.10637616003926767 loss:0.7243577306973332
Epoch:50 w1:1.2785559969021467 w2:1.0055227596103504, bias:-1.0258724765739597 loss:0.6114339582491788
Epoch:100 w1:1.788621655709841 w2:1.1344654186362522, bias:-1.3236095092556865 loss:0.5966810319645302
Epoch:150 w1:2.2664873793409406 w2:1.194168836471839, bias:-1.5626738119183785 loss:0.585067308863362
Epoch:200 w1:2.7049523884882483 w2:1.2318953430207635, bias:-1.770880176873801 loss:0.5755511931805534
Epoch:250 w1:3.1050753862491134 w2:1.2624387432636692, bias:-1.9583574657355072 loss:0.5676764252930397
Epoch:300 w1:3.4701595704123336 w2:1.2903893627255825, bias:-2.129500185010153 loss:0.5611199821484074
Epoch:350 w1:3.8038488189659816 w2:1.317102917222769, bias:-2.286721914781275 loss:0.5556308679871667
Epoch:400 w1:4.109552542773094 w2:1.342924022756863, bias:-2.4316724642422405 loss:0.5510110545075328
Epoch:402 w1:4.121242825414516 w2:1.3439393459382403, bias:-2.4372343828197

In [24]:
customModel.predict(x_test)

9     0.805442
12    0.210071
4     0.690504
10    0.413026
14    0.610077
11    0.515159
dtype: float64